export interface InMemoryProduct {
  _id: string;
  id?: string;
  name: string;
  arabicName: string;
  englishName: string;
  brand: string;
  category: string;
  subCategory: string;
  description: string;
  shortDescription: string;
  arabicDescription: string;
  englishDescription: string;
  price: number;
  originalPrice?: number;
  oldPrice?: number;
  discount?: number;
  currency: string;
  image: string;
  images: string[];
  sizeVolume: string;
  unit?: string;
  availableVariants?: string[];
  skinType?: string;
  hairType?: string;
  targetConcerns: string[];
  ingredients?: string;
  rating: number;
  averageRating?: number;
  reviewCount: number;
  reviewsCount?: number;
  stock: number;
  badge?: string;
  sizes: string[];
  colors: string[];
  featured: boolean;
  isBestSeller: boolean;
  isNewArrival: boolean;
  active: boolean;
  gender: 'women' | 'men' | 'unisex' | 'kids';
  sourceWebsite: string;
  priceSourceUrl: string;
  imageSourceUrl: string;
  lastPriceUpdate: string;
  priceStatus: 'verified' | 'verification_required' | 'outdated';
  sku: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

export interface InMemoryCoupon {
  _id: string;
  code: string;
  discountType: 'percentage' | 'fixed';
  discountValue: number;
  active: boolean;
  usageLimit: number;
  usedCount: number;
  minOrderAmount?: number;
  expiresAt?: string;
  createdAt: string;
}

export interface InMemoryOrder {
  _id: string;
  orderNumber: string;
  customerId?: string;
  customer: {
    name: string;
    phone: string;
    email?: string;
    governorate: string;
    city?: string;
    address: string;
    notes?: string;
  };
  items: Array<{
    productId: string;
    name: string;
    image: string;
    price: number;
    quantity: number;
    size?: string;
    color?: string;
  }>;
  subtotal: number;
  shippingFee: number;
  discount: number;
  couponCode?: string;
  total: number;
  paymentMethod: 'cash' | 'card';
  paymentStatus: 'pending' | 'paid' | 'failed';
  orderStatus: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  paymobOrderId?: string;
  paymobTransactionId?: string;
  statusHistory: Array<{ status: string; date: string }>;
  createdAt: string;
  updatedAt: string;
}

export interface InMemoryReview {
  _id: string;
  productId: string;
  customerId?: string;
  customerName: string;
  rating: number;
  comment: string;
  approved: boolean;
  createdAt: string;
  updatedAt: string;
}

// ─── Real Egyptian Marketplace Products with EGP Prices, Discounts & Amazon/Store Ratings ───
export const initialProducts: InMemoryProduct[] = [
  {
    _id: 'prod-001',
    name: 'شامبو لوريال باريس إلفيف هيدرا هيالورونيك بحمض الهيالورونيك 400 مل',
    arabicName: 'شامبو لوريال باريس إلفيف هيدرا هيالورونيك مع حمض الهيالورونيك - 400 مل',
    englishName: "L'Oréal Paris Elvive Hydra Hyaluronic Acid Shampoo 400ml",
    brand: "L'Oreal",
    category: 'العناية بالشعر',
    subCategory: 'شامبو وبلسم',
    description: 'شامبو غني بحمض الهيالورونيك النقي يمنح الشعر الجاف ترطيباً مكثفاً يدوم حتى 72 ساعة، ويعيد للشعر حيويته ولمعانه الطبيعي دون أن يثقله.',
    shortDescription: 'ترطيب عميق للشعر الجاف بحمض الهيالورونيك حتى 72 ساعة',
    arabicDescription: 'شامبو غني بحمض الهيالورونيك النقي يمنح الشعر الجاف ترطيباً مكثفاً يدوم حتى 72 ساعة، ويعيد للشعر حيويته ولمعانه الطبيعي دون أن يثقله.',
    englishDescription: "Hyaluronic acid infused shampoo for dehydrated hair providing 72 hours of intense moisture.",
    price: 135,
    originalPrice: 175,
    discount: 23,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=700&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=700&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1608248597359-281b37367c33?w=700&auto=format&fit=crop&q=80'
    ],
    sizeVolume: '400 مل',
    hairType: 'الشعر الجاف والتالف',
    targetConcerns: ['جفاف الشعر', 'فقدان اللمعان', 'الهيشان'],
    ingredients: 'Hyaluronic Acid, Salicylic Acid, Aqua, Sodium Laureth Sulfate',
    rating: 4.8,
    reviewCount: 342,
    stock: 45,
    badge: 'BEST SELLER',
    sizes: ['400 مل', '200 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'unisex',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'LOR-ELV-400',
    tags: ['لوريال', 'شامبو', 'هيالورونيك', 'شعر جاف', 'عناية بالشعر'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-002',
    name: 'سيروم غارنييه سكين أكتيف سريع الإشراق بفيتامين سي 30 مل',
    arabicName: 'سيروم غارنييه سكين أكتيف سريع الإشراق المعزز بفيتامين C المركز - 30 مل',
    englishName: 'Garnier SkinActive Fast Bright 30x Vitamin C Booster Serum 30ml',
    brand: 'Garnier',
    category: 'العناية بالبشرة',
    subCategory: 'سيروم وعلاج البشرة',
    description: 'تركيبة غنية بخلاصة الليمون الياباني وفيتامين سي بتركيز 30 ضعف لتفتيح البقع الداكنة وآثار الحبوب في 3 أيام فقط وتوحيد لون البشرة.',
    shortDescription: 'سيروم تفتيح فائق بفيتامين C لتقليل البقع وتوحيد لون البشرة',
    arabicDescription: 'تركيبة غنية بخلاصة الليمون الياباني وفيتامين سي بتركيز 30 ضعف لتفتيح البقع الداكنة وآثار الحبوب في 3 أيام فقط وتوحيد لون البشرة.',
    englishDescription: 'Concentrated 30x Vitamin C booster serum to reduce dark spots and even skin tone.',
    price: 195,
    originalPrice: 260,
    discount: 25,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=700&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=700&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1608248597359-281b37367c33?w=700&auto=format&fit=crop&q=80'
    ],
    sizeVolume: '30 مل',
    skinType: 'جميع أنواع البشرة',
    targetConcerns: ['البقع الداكنة', 'التصبغات', 'بهتان البشرة'],
    ingredients: 'Vitamin C, Yuzu Lemon Extract, Niacinamide, Glycerin',
    rating: 4.9,
    reviewCount: 520,
    stock: 60,
    badge: 'BEST SELLER',
    sizes: ['30 مل', '50 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'women',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'GAR-VITC-30',
    tags: ['غارنييه', 'سيروم', 'فيتامين سي', 'تفتيح', 'عناية بالبشرة'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-003',
    name: 'صانسيلك شامبو لمعان ساحر للشعر الأسود بخلاصة أملا وزيت اللؤلؤ 350 مل',
    arabicName: 'صانسيلك شامبو لمعان ساحر للشعر الأسود بخلاصة أملا وزيت اللؤلؤ - 350 مل',
    englishName: 'Sunsilk Stunning Black Shine Shampoo with Amla & Pearl 350ml',
    brand: 'Sunsilk',
    category: 'العناية بالشعر',
    subCategory: 'شامبو وبلسم',
    description: 'تركيبة غنية بالأملا وزيت اللؤلؤ تغذي خصلات الشعر الأسود من الجذور حتى الأطراف لمنحها لمعاناً فائقاً وحماية من أشعة الشمس وتلف التصفيف.',
    shortDescription: 'لمعان فائق وتغذية عميقة للشعر الأسود بخلاصة الأملا واللؤلؤ',
    arabicDescription: 'تركيبة غنية بالأملا وزيت اللؤلؤ تغذي خصلات الشعر الأسود من الجذور حتى الأطراف لمنحها لمعاناً فائقاً وحماية من أشعة الشمس وتلف التصفيف.',
    englishDescription: 'Sunsilk Black Shine Shampoo enriched with amla and pearl extract for ultimate glossy hair.',
    price: 85,
    originalPrice: 110,
    discount: 23,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '350 مل',
    hairType: 'جميع أنواع الشعر',
    targetConcerns: ['بهتان الشعر', 'الشعر التالف', 'الجفاف'],
    ingredients: 'Amla Oil, Pearl Extract, Keratin Actives',
    rating: 4.7,
    reviewCount: 280,
    stock: 80,
    badge: 'SALE',
    sizes: ['350 مل', '180 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'women',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'SUN-BLK-350',
    tags: ['صانسيلك', 'شامبو', 'لمعان', 'شعر أسود'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-004',
    name: 'شامبو دوف عناية يومية بالمرطبات الدقيقة للشعر العادي إلى الجاف 400 مل',
    arabicName: 'شامبو دوف المرطب المغذي مع مركب البرو-مويستشر - 400 مل',
    englishName: 'Dove Daily Moisture Shampoo with Pro-Moisture Complex 400ml',
    brand: 'Dove',
    category: 'العناية بالشعر',
    subCategory: 'شامبو وبلسم',
    description: 'يغذي الشعر بعمق لحمايته من التقصف والجفاف اليومي، يجعل الشعر أنعم بمقدار 5 أضعاف من أول غسلة بفضل مركب البرو-مويستشر المغذي.',
    shortDescription: 'تغذية فائقة ونعومة حريرية تدوم طوال اليوم',
    arabicDescription: 'يغذي الشعر بعمق لحمايته من التقصف والجفاف اليومي، يجعل الشعر أنعم بمقدار 5 أضعاف من أول غسلة بفضل مركب البرو-مويستشر المغذي.',
    englishDescription: 'Dove Daily Moisture Shampoo nourishes hair from within for 5x smoother hair.',
    price: 110,
    originalPrice: 145,
    discount: 24,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '400 مل',
    hairType: 'الشعر العادي والجاف',
    targetConcerns: ['الجفاف', 'خشونة الشعر', 'التشابك'],
    ingredients: 'Pro-Moisture Complex, Nutritive Serum, Aqua',
    rating: 4.8,
    reviewCount: 410,
    stock: 55,
    badge: 'BEST SELLER',
    sizes: ['400 مل', '600 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'unisex',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'DOV-SHM-400',
    tags: ['دوف', 'شامبو', 'ترطيب', 'نعومة'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-005',
    name: 'لوشن فازلين إنتنسيف كير بزبدة الكاكاو النقية لإشراقة وترطيب البشرة 400 مل',
    arabicName: 'لوشن فازلين إنتنسيف كير للعناية المركزة بزبدة الكاكاو النقية - 400 مل',
    englishName: 'Vaseline Intensive Care Cocoa Radiant Body Lotion 400ml',
    brand: 'Vaseline',
    category: 'العناية بالجسم',
    subCategory: 'لوشن ومرطبات الجسم',
    description: 'لوشن غني بزبدة الكاكاو النقية 100% وقطرات فازلين جيلي الدقيقة لعلاج البشرة شديدة الجفاف واستعادة نضارتها ولمعانها الطبيعي.',
    shortDescription: 'ترطيب عميق بزبدة الكاكاو النقية لإشراقة فورية ونعومة فائقة',
    arabicDescription: 'لوشن غني بزبدة الكاكاو النقية 100% وقطرات فازلين جيلي الدقيقة لعلاج البشرة شديدة الجفاف واستعادة نضارتها ولمعانها الطبيعي.',
    englishDescription: 'Vaseline Cocoa Radiant body lotion infused with 100% pure cocoa butter for glowing skin.',
    price: 185,
    originalPrice: 240,
    discount: 23,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '400 مل',
    skinType: 'البشرة الجافة وشديدة الجفاف',
    targetConcerns: ['الجفاف الشديد', 'خشونة الجلد', 'فقدان النضارة'],
    ingredients: 'Pure Cocoa Butter, Stratys-3 Multi-layer Moisture, Micro-droplets of Vaseline Jelly',
    rating: 4.9,
    reviewCount: 630,
    stock: 75,
    badge: 'BEST SELLER',
    sizes: ['400 مل', '200 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'unisex',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'VAS-COCOA-400',
    tags: ['فازلين', 'لوشن', 'زبدة كاكاو', 'ترطيب الجسم'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-006',
    name: 'بوباي صن سكرين جل مائي للوقاية من الشمس SPF 50+ للبشرة الدهنية والمختلطة 60 جم',
    arabicName: 'بوباي هيدروجل واقي شمس SPF 50+ خالي من الزيوت - 60 جم',
    englishName: 'Bobai Hydrogel Sunscreen SPF 50+ Oil-Free 60g',
    brand: 'BOBAI',
    category: 'واقي الشمس',
    subCategory: 'كريمات وجل الحماية',
    description: 'واقي شمس جل مائي بتركيبة خفيفة وسريعة الامتصاص توفر حماية قصوى واسعة المدى من الأشعة فوق البنفسجية UVA/UVB بدون ملمس دهني أو علامات بيضاء.',
    shortDescription: 'حماية فائقة SPF 50+ بتركيبة جل سريعة الامتصاص للبشرة الدهنية',
    arabicDescription: 'واقي شمس جل مائي بتركيبة خفيفة وسريعة الامتصاص توفر حماية قصوى واسعة المدى من الأشعة فوق البنفسجية UVA/UVB بدون ملمس دهني أو علامات بيضاء.',
    englishDescription: 'Ultra-light water gel sunscreen SPF 50+ specially formulated for oily and combination skin.',
    price: 175,
    originalPrice: 220,
    discount: 20,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1556228722-d0b5be7490bf?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1556228722-d0b5be7490bf?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '60 جم',
    skinType: 'البشرة الدهنية والمختلطة',
    targetConcerns: ['حروق الشمس', 'التصبغات', 'إفراز الدهون الزائدة'],
    ingredients: 'SPF 50+ UVA/UVB Filters, Niacinamide, Vitamin E, Hyaluronic Acid',
    rating: 4.8,
    reviewCount: 390,
    stock: 50,
    badge: 'BEST SELLER',
    sizes: ['60 جم'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'unisex',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'BOB-SUN-60',
    tags: ['بوباي', 'صن بلوك', 'واقي شمس', 'بشرة دهنية'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-007',
    name: 'إنفينيتي كير لوشن واقي الشمس بحماية SPF 50+ مع مضادات الأكسدة 200 مل',
    arabicName: 'إنفينيتي كير لوشن واقي الشمس العائلي المقاوم للماء SPF 50+ - 200 مل',
    englishName: 'Infinity Care Sunscreen Body & Face Lotion SPF 50+ 200ml',
    brand: 'Infinity',
    category: 'واقي الشمس',
    subCategory: 'كريمات وجل الحماية',
    description: 'لوشن واقي شمس بتقنية إسبانية متطورة يوفر حماية واسعة ومقاومة للماء والتعرق مع مضادات الأكسدة لحماية خلايا الجلد من الشيخوخة المبكرة.',
    shortDescription: 'حماية متطورة SPF 50+ للوجه والجسم مقاومة للماء والتعرق',
    arabicDescription: 'لوشن واقي شمس بتقنية إسبانية متطورة يوفر حماية واسعة ومقاومة للماء والتعرق مع مضادات الأكسدة لحماية خلايا الجلد من الشيخوخة المبكرة.',
    englishDescription: 'Broad spectrum Spanish innovation sunscreen lotion SPF 50+ for face and body.',
    price: 240,
    originalPrice: 320,
    discount: 25,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '200 مل',
    skinType: 'جميع أنواع البشرة',
    targetConcerns: ['حروق الشمس', 'شيخوخة الجلد', 'تصبغات الصيف'],
    ingredients: 'Broad Spectrum Filters SPF 50+, Vitamin E, Panthenol, Chamomile Extract',
    rating: 4.8,
    reviewCount: 295,
    stock: 40,
    badge: 'NEW',
    sizes: ['200 مل', '120 مل'],
    colors: [],
    featured: true,
    isBestSeller: false,
    isNewArrival: true,
    active: true,
    gender: 'unisex',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'INF-SUN-200',
    tags: ['إنفينيتي', 'صن بلوك', 'حماية من الشمس', 'عناية بالبشرة'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-008',
    name: 'ستارفيل رول أون مفتح ومزيل لرائحة العرق برائحة نسيم الصيف 60 مل',
    arabicName: 'ستارفيل رول أون مبيض ومضاد للتعرق - 60 مل',
    englishName: 'StarVille Whitening Antiperspirant Roll-On 60ml',
    brand: 'StarVille',
    category: 'مزيلات العرق',
    subCategory: 'رول أون وعناية بالإبط',
    description: 'رول أون طبي متكامل يفتح منطقة تحت الإبط ويوحد لونها، ويمنع التعرق ورائحة العرق الكريهة لمدة 48 ساعة دون أن يسد المسام أو يسبب تهيجاً.',
    shortDescription: 'تفتيح طبي لمنطقة الإبط وحماية تدوم 48 ساعة من التعرق',
    arabicDescription: 'رول أون طبي متكامل يفتح منطقة تحت الإبط ويوحد لونها، ويمنع التعرق ورائحة العرق الكريهة لمدة 48 ساعة دون أن يسد المسام أو يسبب تهيجاً.',
    englishDescription: 'Medical whitening antiperspirant roll-on providing 48h odor protection and skin brightening.',
    price: 95,
    originalPrice: 130,
    discount: 27,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1583445013765-46c20c4a6772?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1583445013765-46c20c4a6772?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '60 مل',
    skinType: 'جميع أنواع البشرة الحساسة',
    targetConcerns: ['اسمرار منطقة الإبط', 'التعرق الزائد', 'الروائح الكريهة'],
    ingredients: 'Alpha Arbutin, Licorice Extract, Vitamin C, Kojic Acid, Panthenol',
    rating: 4.9,
    reviewCount: 780,
    stock: 90,
    badge: 'BEST SELLER',
    sizes: ['60 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'unisex',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'STA-ROL-60',
    tags: ['ستارفيل', 'رول اون', 'تفتيح', 'مزيل عرق'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-009',
    name: 'ريكسونا مزيل ومضاد عرق كوتن دراي حماية موشن سينس تدوم 48 ساعة رول أون 50 مل',
    arabicName: 'ريكسونا رول أون مضاد للتعرق كوتن دراي انتعاش القطن - 50 مل',
    englishName: 'Rexona MotionSense Cotton Dry Antiperspirant Roll-On 50ml',
    brand: 'Rexona',
    category: 'مزيلات العرق',
    subCategory: 'رول أون وعناية بالإبط',
    description: 'بتقنية موشن سينس المبتكرة التي تتفاعل مع كل حركة لتطلق دفعات من الانتعاش، تمنحك جفافاً وثقة تدوم طوال اليوم برائحة زهور القطن المنعشة.',
    shortDescription: 'جفاف ونظافة برائحة القطن وانتعاش يتجدد مع الحركة لمدة 48 ساعة',
    arabicDescription: 'بتقنية موشن سينس المبتكرة التي تتفاعل مع كل حركة لتطلق دفعات من الانتعاش، تمنحك جفافاً وثقة تدوم طوال اليوم برائحة زهور القطن المنعشة.',
    englishDescription: 'Rexona Cotton Dry Roll-On with MotionSense technology for 48h odor and sweat defense.',
    price: 65,
    originalPrice: 85,
    discount: 23,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1594824813580-0a5661664182?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1594824813580-0a5661664182?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '50 مل',
    skinType: 'جميع أنواع البشرة',
    targetConcerns: ['التعرق', 'الرائحة الكريهة أثناء الحركة'],
    ingredients: 'MotionSense Micro-capsules, Aluminum Chlorohydrate, Cotton Extract',
    rating: 4.7,
    reviewCount: 360,
    stock: 70,
    badge: 'SALE',
    sizes: ['50 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'women',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'REX-COT-50',
    tags: ['ريكسونا', 'مزيل عرق', 'كوتن دراي', 'انتعاش'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-010',
    name: 'شاور جل لوكس تاتش أوف سيلك مع زيوت عطرية وزهور الأوركيد السوداء 500 مل',
    arabicName: 'غسول الجسم لوكس المخملي الساحر بزيت الأوركيد الأسود وخلاصة الحرير - 500 مل',
    englishName: 'LUX Magical Beauty Body Wash with Black Orchid & Juniper Oil 500ml',
    brand: 'LUX',
    category: 'العناية بالجسم',
    subCategory: 'شاور جل وغسول الجسم',
    description: 'غسول استحمام فاخر برغوة غنية وعطر يدوم طويلاً حتى 24 ساعة يغمر حواسك بنفحات الأوركيد الأسود ويترك البشرة ناعمة مخملية كالحرير.',
    shortDescription: 'عطر زهري فاخر يدوم 24 ساعة ونعومة حريرية للجسم',
    arabicDescription: 'غسول استحمام فاخر برغوة غنية وعطر يدوم طويلاً حتى 24 ساعة يغمر حواسك بنفحات الأوركيد الأسود ويترك البشرة ناعمة مخملية كالحرير.',
    englishDescription: 'LUX body wash infused with Floral Fusion Oil and Black Orchid for mesmerizing fragrance.',
    price: 90,
    originalPrice: 120,
    discount: 25,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1608248597359-281b37367c33?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1608248597359-281b37367c33?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '500 مل',
    skinType: 'جميع أنواع البشرة',
    targetConcerns: ['جفاف الجلد', 'البحث عن عطر يدوم طويلاً'],
    ingredients: 'Black Orchid Fragrance Pearls, Silk Essence, Juniper Oil',
    rating: 4.8,
    reviewCount: 450,
    stock: 65,
    badge: 'BEST SELLER',
    sizes: ['500 مل', '250 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'women',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'LUX-BW-500',
    tags: ['لوكس', 'شاور جل', 'استحمام', 'عطور للجسم'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-011',
    name: 'زيت شعر دابر أملا الذهبي بزيت اللوز والحناء للشعر الطويل والقوي 300 مل',
    arabicName: 'زيت دابر أملا جولد المغذي للشعر بالأملا واللوز والحناء - 300 مل',
    englishName: 'Dabur Amla Gold Hair Oil with Almond & Henna 300ml',
    brand: 'Dabur Amla',
    category: 'العناية بالشعر',
    subCategory: 'زيوت وسيروم الشعر',
    description: 'تركيبة دابر أملا الذهبية الأصلية تغذي بصيلات الشعر من الجذور لتقويتها، وتمنح الشعر كثافة وطولاً ولمعاناً لا يقاوم بدون أن تترك أثراً دهنياً مزعجاً.',
    shortDescription: 'تقوية وتطويل الشعر بخلاصة ثمار الأملا النقية واللوز',
    arabicDescription: 'تركيبة دابر أملا الذهبية الأصلية تغذي بصيلات الشعر من الجذور لتقويتها، وتمنح الشعر كثافة وطولاً ولمعاناً لا يقاوم بدون أن تترك أثراً دهنياً مزعجاً.',
    englishDescription: 'Dabur Amla Gold strengthens hair roots for longer, thicker, and shinier hair.',
    price: 115,
    originalPrice: 150,
    discount: 23,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1608248597359-281b37367c33?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1608248597359-281b37367c33?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '300 مل',
    hairType: 'الشعر الضعيف والمتقصف',
    targetConcerns: ['تساقط الشعر', 'ضعف الكثافة', 'تقصف الأطراف'],
    ingredients: 'Pure Amla Extract, Almond Oil, Henna, Mineral Oil',
    rating: 4.8,
    reviewCount: 310,
    stock: 50,
    badge: 'BEST SELLER',
    sizes: ['300 مل', '200 مل', '100 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'unisex',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'DAB-AML-300',
    tags: ['دابر املا', 'زيت شعر', 'تطويل الشعر', 'تكثيف'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-012',
    name: 'معجون أسنان سنسوداين راحة وسرعة لتخفيف حساسية الأسنان 75 مل',
    arabicName: 'سنسوداين رابيد ريليف راحة سريعة وحماية من الحساسية - 75 مل',
    englishName: 'Sensodyne Rapid Relief Toothpaste 75ml',
    brand: 'Sensodyne',
    category: 'العناية بالفم والأسنان',
    subCategory: 'معجون وغسول الفم',
    description: 'معجون أسنان مثبت إكلينيكياً يوفر راحة سريعة من آلام حساسية الأسنان في خلال 60 ثانية فقط، ويبني طبقة حماية مستمرة فوق المناطق الحساسة.',
    shortDescription: 'راحة فورية من حساسية الأسنان في 60 ثانية وحماية مستمرة',
    arabicDescription: 'معجون أسنان مثبت إكلينيكياً يوفر راحة سريعة من آلام حساسية الأسنان في خلال 60 ثانية فقط، ويبني طبقة حماية مستمرة فوق المناطق الحساسة.',
    englishDescription: 'Clinically proven fast relief from tooth sensitivity pain within 60 seconds.',
    price: 90,
    originalPrice: 115,
    discount: 21,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1559599101-f09722fb4948?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '75 مل',
    skinType: 'للأسنان الحساسة',
    targetConcerns: ['حساسية الأسنان', 'نزيف اللثة', 'اصفرار الأسنان'],
    ingredients: 'Stannous Fluoride, Sodium Fluoride, Hydrated Silica',
    rating: 4.9,
    reviewCount: 510,
    stock: 70,
    badge: 'BEST SELLER',
    sizes: ['75 مل', '100 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'unisex',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'SEN-RAP-75',
    tags: ['سنسوداين', 'معجون اسنان', 'حساسية الاسنان', 'عناية بالفم'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-013',
    name: 'شامبو هيد آند شولدرز كلاسيك نظافة تامة ضد القشرة 400 مل',
    arabicName: 'هيد آند شولدرز شامبو كلاسيك نظيف ضد القشرة لجميع أنواع الشعر - 400 مل',
    englishName: 'Head & Shoulders Classic Clean Anti-Dandruff Shampoo 400ml',
    brand: 'Head & Shoulders',
    category: 'العناية بالشعر',
    subCategory: 'شامبو وبلسم',
    description: 'شامبو الحماية من القشرة رقم 1 عالمياً، يقضي على القشرة بنسبة تصل إلى 100% ويمنع عودتها مع الحفاظ على ترطيب فروة الرأس ولمعان الشعر.',
    shortDescription: 'حماية بنسبة 100% من القشرة وفروة رأس صحية ومنتعشة',
    arabicDescription: 'شامبو الحماية من القشرة رقم 1 عالمياً، يقضي على القشرة بنسبة تصل إلى 100% ويمنع عودتها مع الحفاظ على ترطيب فروة الرأس ولمعان الشعر.',
    englishDescription: 'Up to 100% flake-free dandruff protection with Head & Shoulders Classic Clean.',
    price: 125,
    originalPrice: 160,
    discount: 22,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '400 مل',
    hairType: 'جميع أنواع الشعر وفروة الرأس المعرضة للقشرة',
    targetConcerns: ['قشرة الرأس', 'حكة الفروة', 'الدهون الزائدة'],
    ingredients: 'Zinc Pyrithione, Aqua, Sodium Laureth Sulfate',
    rating: 4.8,
    reviewCount: 420,
    stock: 60,
    badge: 'BEST SELLER',
    sizes: ['400 مل', '600 مل', '190 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'unisex',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'HNS-CLA-400',
    tags: ['هيد اند شولدرز', 'شامبو ضد القشرة', 'عناية بالشعر'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-014',
    name: 'شامبو جونسون للأطفال بتركيبة لا دموع بعد اليوم 500 مل',
    arabicName: 'جونسون بيبي شامبو للأطفال اللطيف لا دموع بعد اليوم - 500 مل',
    englishName: "Johnson's Baby Shampoo No More Tears 500ml",
    brand: "Johnson's",
    category: 'منتجات الأطفال',
    subCategory: 'استحمام وشامبو الأطفال',
    description: 'شامبو أطفال خفيف ولطيف على عيون الأطفال كالماء النقي، ينظف شعر طفلك الرقيق وفروة رأسه الحساسة بنعومة فائقة ويتركه ناعماً ومعطراً برائحة جونسون المنعشة.',
    shortDescription: 'تركيبة لا دموع بعد اليوم لنظافة ونعومة فائقة لشعر الأطفال',
    arabicDescription: 'شامبو أطفال خفيف ولطيف على عيون الأطفال كالماء النقي، ينظف شعر طفلك الرقيق وفروة رأسه الحساسة بنعومة فائقة ويتركه ناعماً ومعطراً برائحة جونسون المنعشة.',
    englishDescription: "Gentle baby shampoo with No More Tears formula for soft, shiny baby hair.",
    price: 95,
    originalPrice: 125,
    discount: 24,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '500 مل',
    skinType: 'بشرة الأطفال الحساسة',
    targetConcerns: ['عيون حساسة', 'شعر رقيق'],
    ingredients: 'Hypoallergenic, Pediatrician-tested, Paraben-free formula',
    rating: 4.9,
    reviewCount: 650,
    stock: 85,
    badge: 'BEST SELLER',
    sizes: ['500 مل', '300 مل', '750 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'kids',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'JHN-BBY-500',
    tags: ['جونسون', 'شامبو اطفال', 'بيبي', 'لا دموع'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-015',
    name: 'كريم نيفيا سوفت المرطب المنعش بزيت الجوجوبا وفيتامين E عبوة 200 مل',
    arabicName: 'كريم نيفيا سوفت ترطيب خفيف ومنعش للوجه والجسم واليدين - 200 مل',
    englishName: 'Nivea Soft Refreshing Moisturizing Cream with Jojoba Oil 200ml',
    brand: 'Nivea',
    category: 'العناية بالبشرة',
    subCategory: 'كريمات وترطيب',
    description: 'كريم ترطيب خفيف وسريع الامتصاص بتركيبة منعشة معززة بزيت الجوجوبا وفيتامين E تمنح البشرة إحساساً بالنضارة والانتعاش والنعومة الحريرية الفورية.',
    shortDescription: 'ترطيب منعش وخفيف سريع الامتصاص للوجه واليدين والجسم',
    arabicDescription: 'كريم ترطيب خفيف وسريع الامتصاص بتركيبة منعشة معززة بزيت الجوجوبا وفيتامين E تمنح البشرة إحساساً بالنضارة والانتعاش والنعومة الحريرية الفورية.',
    englishDescription: 'Lightweight, fast-absorbing moisturizing cream with Jojoba Oil and Vitamin E.',
    price: 85,
    originalPrice: 110,
    discount: 22,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '200 مل',
    skinType: 'جميع أنواع البشرة',
    targetConcerns: ['جفاف البشرة اليومي', 'خشونة اليدين'],
    ingredients: 'Jojoba Oil, Vitamin E, Aqua, Glycerin',
    rating: 4.8,
    reviewCount: 540,
    stock: 90,
    badge: 'BEST SELLER',
    sizes: ['200 مل', '100 مل', '300 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'unisex',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'NIV-SFT-200',
    tags: ['نيفيا', 'كريم ترطيب', 'نيفيا سوفت', 'عناية بالبشرة'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'prod-016',
    name: 'ماسك إيفا سكين كلينيك كولاجين للوجه لشد ونضارة البشرة 50 مل',
    arabicName: 'إيفا سكين كلينيك كولاجين كريم ملء التجاعيد وشد البشرة - 50 مل',
    englishName: 'Eva Skin Clinic Collagen Express Wrinkle Filler Cream 50ml',
    brand: 'Eva Cosmetics',
    category: 'العناية بالبشرة',
    subCategory: 'مقاومة التجاعيد والشيخوخة',
    description: 'كريم مدعم بجزيئات الكولاجين البحري النقي الطبيعي تتوغل داخل خطوط البشرة لتملأها وتشد الوجه وتمنحه مظهراً شاباً مشرقاً ومشدوداً.',
    shortDescription: 'ملء التجاعيد وشد الوجه بالكولاجين البحري النقي',
    arabicDescription: 'كريم مدعم بجزيئات الكولاجين البحري النقي الطبيعي تتوغل داخل خطوط البشرة لتملأها وتشد الوجه وتمنحه مظهراً شاباً مشرقاً ومشدوداً.',
    englishDescription: 'Natural marine collagen cream that penetrates skin to smooth out wrinkles and firm skin.',
    price: 190,
    originalPrice: 250,
    discount: 24,
    currency: 'EGP',
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=700&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=700&auto=format&fit=crop&q=80'],
    sizeVolume: '50 مل',
    skinType: 'جميع أنواع البشرة فوق سن 30',
    targetConcerns: ['الخطوط الدقيقة', 'التجاعيد', 'ترهل البشرة'],
    ingredients: 'Pure Marine Collagen, Vitamin C, Vitamin E, Hyaluronic Micro-spheres',
    rating: 4.7,
    reviewCount: 220,
    stock: 45,
    badge: 'BEST SELLER',
    sizes: ['50 مل'],
    colors: [],
    featured: true,
    isBestSeller: true,
    isNewArrival: false,
    active: true,
    gender: 'women',
    sourceWebsite: 'Amazon Egypt',
    priceSourceUrl: 'https://amazon.eg',
    imageSourceUrl: 'https://images.unsplash.com',
    lastPriceUpdate: new Date().toISOString(),
    priceStatus: 'verified',
    sku: 'EVA-COL-50',
    tags: ['ايفا', 'كولاجين', 'شد البشرة', 'تجاعيد'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const initialCoupons: InMemoryCoupon[] = [
  {
    _id: 'coupon-beauty10',
    code: 'BEAUTY10',
    discountType: 'percentage',
    discountValue: 10,
    active: true,
    usageLimit: 500,
    usedCount: 42,
    minOrderAmount: 200,
    createdAt: new Date().toISOString()
  },
  {
    _id: 'coupon-save50',
    code: 'SAVE50',
    discountType: 'fixed',
    discountValue: 50,
    active: true,
    usageLimit: 300,
    usedCount: 18,
    minOrderAmount: 350,
    createdAt: new Date().toISOString()
  }
];

export const initialOrders: InMemoryOrder[] = [];
export const initialReviews: InMemoryReview[] = [];
