import express from'express';import cors from'cors';import jwt from'jsonwebtoken';import bcrypt from'bcryptjs';import mongoose from'mongoose';import Product from'../src/models/Product.js';import Order from'../src/models/Order.js';import Admin from'../src/models/Admin.js';import Coupon from'../src/models/Coupon.js';import Review from'../src/models/Review.js';
const app=express();app.use(cors({origin:true,credentials:true}));app.use(express.json({limit:'10mb'}));
let connected=false;async function db(){if(connected||!process.env.MONGODB_URI)return;try{await mongoose.connect(process.env.MONGODB_URI,{serverSelectionTimeoutMS:5000});connected=true}catch(e){console.warn('MongoDB unavailable; API will use safe fallbacks')}}
const secret=()=>process.env.JWT_SECRET||'tammi_sports_default_jwt_secret_dev_2026';
function auth(req:any,res:any,next:any){try{const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(401).json({success:false,error:'Unauthorized'});req.admin=jwt.verify(h.slice(7),secret());next()}catch{return res.status(401).json({success:false,error:'Invalid token'})}}
app.get('/api/health',async(_req,res)=>{await db();res.json({success:true,database:mongoose.connection.readyState===1})});
app.post('/api/admin/login',async(req,res)=>{await db();const{email,password}=req.body||{};try{if(mongoose.connection.readyState===1){const a=await Admin.findOne({email});if(a&&await a.comparePassword(password)){return res.json({success:true,token:jwt.sign({id:a._id,role:a.role},secret(),{expiresIn:'7d'}),admin:{email:a.email,role:a.role}})}}}catch{}const ok=email===(process.env.ADMIN_EMAIL||'admin@tammi.com')&&password===(process.env.ADMIN_PASSWORD||'admin123');if(!ok)return res.status(401).json({success:false,error:'Invalid email or password'});res.json({success:true,token:jwt.sign({id:'local-admin',role:'admin'},secret(),{expiresIn:'7d'}),admin:{email,role:'admin'}})});
app.get('/api/products',async(_req,res)=>{await db();try{if(mongoose.connection.readyState===1)return res.json({success:true,products:await Product.find({active:{$ne:false}}).sort({createdAt:-1})})}catch{}res.json({success:true,products:[]})});
app.get('/api/products/:id',async(req,res)=>{await db();try{if(mongoose.connection.readyState===1){const p=await Product.findById(req.params.id);if(p)return res.json({success:true,product:p})}}catch{}res.status(404).json({success:false,error:'Product not found'})});
app.get('/api/admin/dashboard',auth,async(_req,res)=>{await db();let products=0,orders=0,revenue=0;try{if(mongoose.connection.readyState===1){products=await Product.countDocuments();orders=await Order.countDocuments();const r=await Order.aggregate([{$match:{paymentStatus:'paid'}},{$group:{_id:null,total:{$sum:'$total'}}}]);revenue=r[0]?.total||0}}catch{}res.json({success:true,stats:{products,orders,revenue}})});
app.get('/api/admin/orders',auth,async(_req,res)=>{await db();try{if(mongoose.connection.readyState===1)return res.json({success:true,orders:await Order.find().sort({createdAt:-1})})}catch{}res.json({success:true,orders:[]})});
app.get('/api/reviews',async(_req,res)=>{await db();try{if(mongoose.connection.readyState===1)return res.json({success:true,reviews:await Review.find().sort({createdAt:-1})})}catch{}res.json({success:true,reviews:[]})});
app.get('/api/admin/coupons',auth,async(_req,res)=>{await db();try{if(mongoose.connection.readyState===1)return res.json({success:true,coupons:await Coupon.find().sort({createdAt:-1})})}catch{}res.json({success:true,coupons:[]})});
app.use((err:any,_req:any,res:any,_next:any)=>res.status(500).json({success:false,error:err?.message||'Internal Server Error'}));
export default app;
